import { useEffect, useMemo, useState } from 'react'
import { Alert, Box, Button, Card, Dialog, DialogActions, DialogContent, DialogTitle, LinearProgress, MenuItem, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material'
import { AddOutlined, FileDownloadOutlined, FileUploadOutlined, SendOutlined } from '@mui/icons-material'
import { api, get, post } from '../api/client'
import type { Decision, Intelligence, KPI, Plan, Project, Scenario, Strategy } from '../types'
import { PageHeader } from '../components/PageHeader'
import { StatusChip } from '../components/StatusChip'
import { pageSx } from './ExecutiveDashboard'
import { useAuth } from '../auth/AuthContext'

type Kind = 'strategy' | 'kpi' | 'project' | 'plan' | 'decision' | 'intelligence' | 'scenario'
type Row = Strategy | KPI | Project | Plan | Decision | Intelligence | Scenario
const configs = {
  strategy: { title: 'Strategy Management', description: 'Vision부터 전략목표까지 계층과 버전을 연결합니다.', path: '/api/v1/strategies', permission: 'strategy:*' },
  kpi: { title: 'KPI & Performance', description: '전사 KPI Tree의 목표·실적·달성률을 한 곳에서 관리합니다.', path: '/api/v1/kpis', permission: 'kpi:*' },
  project: { title: 'Project Portfolio', description: '전략 연결성, 효과, 예산과 위험을 경영 관점에서 비교합니다.', path: '/api/v1/projects', permission: 'project:*' },
  plan: { title: 'Business Planning', description: '조직별 사업계획과 선택형 검토·승인 흐름을 관리합니다.', path: '/api/v1/plans', permission: 'plan:own' },
  decision: { title: 'Decision Log', description: '무엇을 왜 결정했는지 근거와 후속 실행을 보존합니다.', path: '/api/v1/decisions', permission: 'decision:*' },
  intelligence: { title: 'Intelligence Hub', description: '시장·경쟁사·규제의 변화와 회사 영향, 위험과 기회를 구조화합니다.', path: '/api/v1/intelligence', permission: 'intelligence:*' },
  scenario: { title: 'Scenario Planning', description: '가정에 따른 예산·프로젝트 영향을 시뮬레이션하고 검토합니다.', path: '/api/v1/scenarios', permission: 'scenario:*' },
} as const

export function EntityPage({ kind }: { kind: Kind }) {
  const cfg = configs[kind]; const { has } = useAuth(); const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [open, setOpen] = useState(false); const [importOpen, setImportOpen] = useState(false); const [form, setForm] = useState<Record<string, string>>({})
  const load = () => { setLoading(true); setError(''); void get<Row[]>(cfg.path).then(setRows).catch(e => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(load, [cfg.path])
  const create = async () => { try { await post(cfg.path, bodyFor(kind, form)); setOpen(false); setForm({}); load() } catch (e) { setError(e instanceof Error ? e.message : '저장하지 못했습니다.') } }
  const submitPlan = async (id: string) => { try { await post(`/api/v1/plans/${id}/submit`); load() } catch (e) { setError(e instanceof Error ? e.message : '제출하지 못했습니다.') } }
  const runScenario = async (id: string) => { try { await post(`/api/v1/scenarios/${id}/run`); load() } catch (e) { setError(e instanceof Error ? e.message : '시뮬레이션하지 못했습니다.') } }
  const canCreate = has(cfg.permission)
  const canImport = ['strategy','kpi','project'].includes(kind) && has('import:*')
  return <Box sx={pageSx}><PageHeader eyebrow={`Enterprise / ${cfg.title}`} title={cfg.title} description={cfg.description} action={<Stack direction="row" spacing={1}>{canImport&&<Button variant="outlined" startIcon={<FileUploadOutlined/>} onClick={()=>setImportOpen(true)}>Excel Import</Button>}{canCreate&&<Button variant="contained" startIcon={<AddOutlined />} onClick={() => setOpen(true)}>새 항목</Button>}</Stack>} />{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}{loading && <LinearProgress />}
    <Card><TableContainer><Table aria-label={`${cfg.title} 목록`}><TableHead><TableRow>{headers(kind).map(h => <TableCell key={h}>{h}</TableCell>)}{(kind === 'plan' || kind === 'scenario') && <TableCell align="right">작업</TableCell>}</TableRow></TableHead><TableBody>{rows.map(row => <EntityRow key={row.id} kind={kind} row={row} submitPlan={submitPlan} runScenario={runScenario} />)}{!loading && rows.length === 0 && <TableRow><TableCell colSpan={headers(kind).length + 1}><Box sx={{ py: 7, textAlign: 'center' }}><Typography fontWeight={700}>아직 등록된 정보가 없습니다.</Typography><Typography variant="body2" color="text.secondary" mt={.5}>권한이 있다면 새 항목을 등록해 시작하세요.</Typography></Box></TableCell></TableRow>}</TableBody></Table></TableContainer></Card>
    <CreateDialog kind={kind} open={open} form={form} setForm={setForm} close={() => setOpen(false)} create={create} />
    {canImport&&<ImportDialog entityType={kind as 'strategy'|'kpi'|'project'} open={importOpen} close={()=>setImportOpen(false)} complete={()=>{setImportOpen(false);load()}}/>}
  </Box>
}

type ImportPreview={id:string;totalRows:number;validRows:number;invalidRows:number;mapping:Record<string,string>;errors:Array<{row:number;field:string;message:string}>;preview:Array<Record<string,string>>}
function ImportDialog({entityType,open,close,complete}:{entityType:'strategy'|'kpi'|'project';open:boolean;close:()=>void;complete:()=>void}){const[file,setFile]=useState<File|null>(null);const[preview,setPreview]=useState<ImportPreview|null>(null);const[error,setError]=useState('');const[busy,setBusy]=useState(false);const inspect=async()=>{if(!file)return;setBusy(true);setError('');try{const data=new FormData();data.set('entityType',entityType);data.set('file',file);setPreview(await api<ImportPreview>('/api/v1/import/preview',{method:'POST',body:data}))}catch(e){setError(e instanceof Error?e.message:'미리보기에 실패했습니다.')}finally{setBusy(false)}};const commit=async()=>{if(!preview)return;setBusy(true);try{await post(`/api/v1/import/${preview.id}/commit`,{});setPreview(null);setFile(null);complete()}catch(e){setError(e instanceof Error?e.message:'Import에 실패했습니다.')}finally{setBusy(false)}};return <Dialog open={open} onClose={close} fullWidth maxWidth="md"><DialogTitle>Excel Import · {entityType}</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><Alert severity="info">Template 다운로드 → Excel 작성 → 검증 미리보기 → 원자적 Import 순서로 진행합니다. 오류가 한 건이라도 있으면 Commit할 수 없습니다.</Alert><Button component="a" href={`/api/v1/import/templates/${entityType}`} startIcon={<FileDownloadOutlined/>} sx={{alignSelf:'flex-start'}}>Template 다운로드</Button><Button component="label" variant="outlined" startIcon={<FileUploadOutlined/>} sx={{alignSelf:'flex-start'}}>{file?.name||'.xlsx 파일 선택'}<input hidden type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>{setFile(e.target.files?.[0]??null);setPreview(null)}}/></Button>{error&&<Alert severity="error">{error}</Alert>}{preview&&<><Stack direction="row" spacing={2}><Typography>전체 <b>{preview.totalRows}</b></Typography><Typography color="success.main">유효 <b>{preview.validRows}</b></Typography><Typography color="error.main">오류 <b>{preview.invalidRows}</b></Typography></Stack>{preview.errors.length>0&&<Alert severity="error">{preview.errors.slice(0,20).map((x,i)=><div key={i}>Row {x.row} · {x.field}: {x.message}</div>)}</Alert>}<Table size="small"><TableHead><TableRow>{Object.keys(preview.preview[0]??{}).map(k=><TableCell key={k}>{k}</TableCell>)}</TableRow></TableHead><TableBody>{preview.preview.slice(0,10).map((row,i)=><TableRow key={i}>{Object.keys(preview.preview[0]??{}).map(k=><TableCell key={k}>{row[k]}</TableCell>)}</TableRow>)}</TableBody></Table></>}</Stack></DialogContent><DialogActions sx={{p:3}}><Button onClick={close}>닫기</Button>{!preview?<Button variant="contained" onClick={inspect} disabled={!file||busy}>검증 미리보기</Button>:<Button variant="contained" onClick={commit} disabled={preview.invalidRows>0||busy}>Import Commit</Button>}</DialogActions></Dialog>}

function EntityRow({ kind, row, submitPlan, runScenario }: { kind: Kind; row: Row; submitPlan: (id: string) => void; runScenario: (id: string) => void }) {
  if (kind === 'strategy') { const r = row as Strategy; return <TableRow hover><TableCell><Typography fontWeight={700}>{r.name}</Typography><Typography variant="body2" color="text.secondary">{r.description || '—'}</Typography></TableCell><TableCell>{r.kind}</TableCell><TableCell>v{r.version}</TableCell><TableCell><StatusChip value={r.status} /></TableCell><TableCell>{r.classification}</TableCell></TableRow> }
  if (kind === 'kpi') { const r = row as KPI; return <TableRow hover><TableCell>{r.code}</TableCell><TableCell><Typography fontWeight={700}>{r.name}</Typography></TableCell><TableCell align="right">{r.target.toLocaleString()} {r.unit}</TableCell><TableCell align="right">{r.actual.toLocaleString()} {r.unit}</TableCell><TableCell sx={{ minWidth: 170 }}><Stack direction="row" spacing={1.5} alignItems="center"><LinearProgress variant="determinate" value={Math.min(r.achievement, 100)} color={r.achievement < 80 ? 'error' : r.achievement < 90 ? 'warning' : 'success'} sx={{ flex: 1, height: 7, borderRadius: 5 }} /><Typography variant="body2" fontWeight={700}>{r.achievement.toFixed(1)}%</Typography></Stack></TableCell><TableCell>{r.frequency}</TableCell></TableRow> }
  if (kind === 'project') { const r = row as Project; return <TableRow hover><TableCell><Typography fontWeight={700}>{r.name}</Typography><Typography variant="body2" color="text.secondary">{r.description || '—'}</Typography></TableCell><TableCell><StatusChip value={r.status} /></TableCell><TableCell>{r.progress.toFixed(0)}%</TableCell><TableCell><StatusChip value={r.risk} /></TableCell><TableCell align="right">₩{r.budget.toLocaleString()}</TableCell><TableCell align="right">₩{r.actualCost.toLocaleString()}</TableCell></TableRow> }
  if (kind === 'plan') { const r = row as Plan; return <TableRow hover><TableCell><Typography fontWeight={700}>{r.title}</Typography></TableCell><TableCell>{r.period}</TableCell><TableCell>v{r.version}</TableCell><TableCell><StatusChip value={r.status} /></TableCell><TableCell>{r.classification}</TableCell><TableCell align="right">{['draft', 'changes_requested'].includes(r.status) && <Button size="small" startIcon={<SendOutlined />} onClick={() => submitPlan(r.id)}>제출</Button>}</TableCell></TableRow> }
  if (kind === 'decision') { const r = row as Decision; return <TableRow hover><TableCell><Typography fontWeight={700}>{r.title}</Typography></TableCell><TableCell>{r.decisionDate?.slice(0, 10) || '—'}</TableCell><TableCell>{r.decision || '—'}</TableCell><TableCell>{r.reason || '—'}</TableCell><TableCell>{r.classification}</TableCell></TableRow> }
  if (kind === 'intelligence') { const r = row as Intelligence; return <TableRow hover><TableCell><Typography fontWeight={700}>{r.title}</Typography><Typography variant="body2" color="text.secondary">{r.summary || '—'}</Typography></TableCell><TableCell>{r.category}</TableCell><TableCell><ChipLike value={r.importance} /></TableCell><TableCell>{r.potentialImpact || '—'}</TableCell><TableCell>{r.recommendedAction || '—'}</TableCell><TableCell>{r.classification}</TableCell></TableRow> }
  const r = row as Scenario; return <TableRow hover><TableCell><Typography fontWeight={700}>{r.name}</Typography><Typography variant="body2" color="text.secondary">{r.description || '—'}</Typography></TableCell><TableCell><StatusChip value={r.status}/></TableCell><TableCell>{String(r.assumptions.costReductionPercent ?? 0)}%</TableCell><TableCell>{r.results ? '결과 생성됨' : '—'}</TableCell><TableCell>{r.classification}</TableCell><TableCell align="right"><Button size="small" onClick={()=>runScenario(r.id)}>Simulation</Button></TableCell></TableRow>
}

function ChipLike({value}:{value:number}) { return <StatusChip value={value >= 80 ? 'critical' : value >= 50 ? 'medium' : 'low'} /> }

function CreateDialog({ kind, open, form, setForm, close, create }: { kind: Kind; open: boolean; form: Record<string, string>; setForm: (v: Record<string, string>) => void; close: () => void; create: () => void }) {
  const field = (key: string) => ({ value: form[key] ?? '', onChange: (e: React.ChangeEvent<HTMLInputElement>) => setForm({ ...form, [key]: e.target.value }) })
  return <Dialog open={open} onClose={close} fullWidth maxWidth="sm"><DialogTitle>{configs[kind].title} 항목 등록</DialogTitle><DialogContent><Stack spacing={2.2} sx={{ pt: 1 }}>
    {kind === 'strategy' && <><TextField label="전략명" required {...field('name')} /><TextField select label="유형" required {...field('kind')}><MenuItem value="vision">Vision</MenuItem><MenuItem value="mission">Mission</MenuItem><MenuItem value="theme">Strategic Theme</MenuItem><MenuItem value="objective">Strategic Objective</MenuItem></TextField><TextField label="설명" multiline minRows={3} {...field('description')} /></>}
    {kind === 'kpi' && <><TextField label="KPI Code" required {...field('code')} /><TextField label="KPI명" required {...field('name')} /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField fullWidth label="목표" type="number" {...field('target')} /><TextField fullWidth label="실적" type="number" {...field('actual')} /><TextField fullWidth label="단위" {...field('unit')} /></Stack></>}
    {kind === 'project' && <><TextField label="프로젝트명" required {...field('name')} /><TextField label="설명" multiline minRows={2} {...field('description')} /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField fullWidth label="진척률" type="number" {...field('progress')} /><TextField fullWidth select label="위험" {...field('risk')}><MenuItem value="low">Low</MenuItem><MenuItem value="medium">Medium</MenuItem><MenuItem value="high">High</MenuItem><MenuItem value="critical">Critical</MenuItem></TextField></Stack><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField fullWidth label="예산" type="number" {...field('budget')} /><TextField fullWidth label="실제 비용" type="number" {...field('actualCost')} /></Stack></>}
    {kind === 'plan' && <><TextField label="계획명" required {...field('title')} /><TextField label="계획 기간 (예: 2027)" required {...field('period')} /><TextField label="계획 개요" multiline minRows={4} {...field('summary')} /></>}
    {kind === 'decision' && <><TextField label="의사결정 제목" required {...field('title')} /><TextField label="결정일" type="date" InputLabelProps={{ shrink: true }} {...field('decisionDate')} /><TextField label="최종 결정" multiline minRows={2} {...field('decision')} /><TextField label="결정 이유" multiline minRows={2} {...field('reason')} /></>}
    {kind === 'intelligence' && <><TextField label="정보 제목" required {...field('title')} /><TextField select label="Category" required {...field('category')}><MenuItem value="competitor">Competitor</MenuItem><MenuItem value="market">Market</MenuItem><MenuItem value="regulation">Regulation</MenuItem><MenuItem value="technology">Technology</MenuItem><MenuItem value="economic">Economic</MenuItem><MenuItem value="investment">Investment</MenuItem><MenuItem value="product">Product</MenuItem></TextField><TextField label="요약" multiline minRows={3} {...field('summary')} /><TextField label="중요도 (0-100)" type="number" {...field('importance')} /><TextField label="예상 영향" {...field('potentialImpact')} /><TextField label="권고 조치" {...field('recommendedAction')} /></>}
    {kind === 'scenario' && <><TextField label="Scenario명" required {...field('name')} /><TextField label="설명" multiline minRows={2} {...field('description')} /><TextField label="비용 감소 가정 (%)" type="number" {...field('costReductionPercent')} /><TextField label="매출 변화 가정 (%)" type="number" {...field('revenueChangePercent')} /></>}
    <TextField select label="보안등급" {...field('classification')}><MenuItem value="internal">Internal</MenuItem><MenuItem value="confidential">Confidential</MenuItem><MenuItem value="executive">Executive</MenuItem><MenuItem value="restricted">Restricted</MenuItem></TextField>
  </Stack></DialogContent><DialogActions sx={{ p: 3 }}><Button onClick={close}>취소</Button><Button variant="contained" onClick={create}>저장</Button></DialogActions></Dialog>
}

function headers(kind: Kind) { if (kind === 'strategy') return ['전략', '유형', '버전', '상태', '보안등급']; if (kind === 'kpi') return ['Code', 'KPI', '목표', '실적', '달성률', '주기']; if (kind === 'project') return ['프로젝트', '상태', '진척률', '위험', '예산', '집행']; if (kind === 'plan') return ['사업계획', '기간', '버전', '상태', '보안등급']; if(kind === 'decision') return ['결정', '결정일', '내용', '이유', '보안등급']; if(kind === 'intelligence') return ['Intelligence','Category','중요도','영향','권고조치','보안등급']; return ['Scenario','상태','비용감소','결과','보안등급'] }
function num(value?: string) { return value ? Number(value) : 0 }
function bodyFor(kind: Kind, f: Record<string, string>) { const common = { classification: f.classification || (kind === 'scenario' ? 'confidential' : 'internal') }; if (kind === 'strategy') return { ...common, name: f.name, kind: f.kind, description: f.description || '' }; if (kind === 'kpi') return { ...common, code: f.code, name: f.name, target: num(f.target), actual: num(f.actual), unit: f.unit || '' }; if (kind === 'project') return { ...common, name: f.name, description: f.description || '', progress: num(f.progress), risk: f.risk || 'low', budget: num(f.budget), actualCost: num(f.actualCost) }; if (kind === 'plan') return { ...common, title: f.title, period: f.period, content: { summary: f.summary || '' } }; if(kind === 'decision') return { ...common, title: f.title, decisionDate: f.decisionDate ? new Date(f.decisionDate).toISOString() : null, decision: f.decision || '', reason: f.reason || '' }; if(kind === 'intelligence') return {...common,title:f.title,category:f.category,summary:f.summary||'',importance:num(f.importance),potentialImpact:f.potentialImpact||'',recommendedAction:f.recommendedAction||''}; return {...common,name:f.name,description:f.description||'',assumptions:{costReductionPercent:num(f.costReductionPercent),revenueChangePercent:num(f.revenueChangePercent)}} }
