import { useEffect, useState } from 'react'
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, Grid, IconButton, MenuItem, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Tooltip, Typography } from '@mui/material'
import { ContentCopyOutlined, DeleteOutline, KeyOutlined, RefreshOutlined } from '@mui/icons-material'
import { del, get, post, put } from '../api/client'
import { PageHeader } from '../components/PageHeader'
import { pageSx } from './ExecutiveDashboard'
import { useAuth } from '../auth/AuthContext'

type KeyRecord={id:string;name:string;prefix:string;scopes:string[];expiresAt?:string;lastUsedAt?:string;revokedAt?:string;createdAt:string}
type KeyPolicy={maxLifetimeDays:number;rotationOverlapHours:number;allowedScopes:string[]}
export function ProfileSecurityPage(){
  const{refresh,user}=useAuth();const[keys,setKeys]=useState<KeyRecord[]>([]);const[policy,setPolicy]=useState<KeyPolicy>({maxLifetimeDays:90,rotationOverlapHours:24,allowedScopes:[]});const[current,setCurrent]=useState('');const[next,setNext]=useState('');const[confirm,setConfirm]=useState('');const[msg,setMsg]=useState('');const[error,setError]=useState('');const[open,setOpen]=useState(false);const[name,setName]=useState('');const[selectedScopes,setSelectedScopes]=useState<string[]>([]);const[expiresInDays,setExpiresInDays]=useState(90);const[issued,setIssued]=useState('')
  const load=()=>{void get<KeyRecord[]>('/api/v1/keys').then(setKeys).catch(e=>setError(e.message));void get<KeyPolicy>('/api/v1/keys/policy').then(value=>{setPolicy(value);setSelectedScopes(current=>current.length?current:value.allowedScopes);setExpiresInDays(current=>Math.min(current,value.maxLifetimeDays))}).catch(e=>setError(e.message))};useEffect(load,[])
  const password=async()=>{setError('');if(next!==confirm){setError('새 비밀번호 확인이 일치하지 않습니다.');return}try{await put('/api/v1/auth/password',{currentPassword:current,newPassword:next});setCurrent('');setNext('');setConfirm('');setMsg('비밀번호를 변경했습니다.');await refresh()}catch(e){setError(e instanceof Error?e.message:'변경 실패')}}
  const issue=async()=>{setError('');try{if(!name.trim()||selectedScopes.length===0)throw new Error('키 이름과 한 개 이상의 Scope를 선택하세요.');const result=await post<{token:string}>('/api/v1/keys',{name,scopes:selectedScopes,expiresInDays});setIssued(result.token);setOpen(false);setName('');load()}catch(e){setError(e instanceof Error?e.message:'키 생성 실패')}}
  const rotate=async(id:string)=>{try{const result=await post<{token:string}>(`/api/v1/keys/${id}/rotate`,{});setIssued(result.token);load()}catch(e){setError(e instanceof Error?e.message:'키 회전 실패')}}
  const revoke=async(id:string)=>{await del(`/api/v1/keys/${id}`);load()}
  return <Box sx={pageSx}><PageHeader eyebrow="Personal / Security" title="비밀번호 및 개인 키" description="개인 API·MCP 키를 직접 발급하고 정책에 따라 회전·폐기합니다. 서비스 관리자 설정과 분리된 개인 보안 영역입니다." />{msg&&<Alert severity="success" sx={{mb:2}}>{msg}</Alert>}{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{issued&&<Alert severity="warning" sx={{mb:3}} action={<Button color="inherit" startIcon={<ContentCopyOutlined/>} onClick={()=>void navigator.clipboard.writeText(issued)}>복사</Button>}><Typography fontWeight={750}>이 키는 지금 한 번만 표시됩니다.</Typography><Typography component="code" sx={{wordBreak:'break-all'}}>{issued}</Typography></Alert>}
    <Grid container spacing={2.5}><Grid size={{xs:12,lg:5}}><Card><CardContent sx={{p:3.5}}><Typography variant="h2">비밀번호 변경</Typography><Typography color="text.secondary" mt={1}>{user?.authMethod==='local'?'로컬 Bootstrap 계정 비밀번호를 변경합니다.':'SSO 계정 비밀번호는 Keycloak에서 관리합니다.'}</Typography><Divider sx={{my:3}}/><Stack spacing={2}><TextField disabled={user?.authMethod!=='local'} label="현재 비밀번호" type="password" value={current} onChange={e=>setCurrent(e.target.value)}/><TextField disabled={user?.authMethod!=='local'} label="새 비밀번호" type="password" helperText="12자 이상" value={next} onChange={e=>setNext(e.target.value)}/><TextField disabled={user?.authMethod!=='local'} label="새 비밀번호 확인" type="password" value={confirm} onChange={e=>setConfirm(e.target.value)}/><Button disabled={user?.authMethod!=='local'} variant="contained" onClick={password} sx={{alignSelf:'flex-start'}}>비밀번호 변경</Button></Stack></CardContent></Card></Grid>
      <Grid size={{xs:12,lg:7}}><Card><CardContent sx={{p:3.5}}><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography variant="h2">개인 API / MCP 키</Typography><Typography color="text.secondary" mt={1}>키 원문은 서버에 저장되지 않습니다. 최대 {policy.maxLifetimeDays}일 · 회전 중첩 {policy.rotationOverlapHours}시간</Typography></Box><Button variant="contained" startIcon={<KeyOutlined/>} onClick={()=>setOpen(true)} disabled={policy.allowedScopes.length===0}>키 발급</Button></Stack><Table sx={{mt:3}}><TableHead><TableRow><TableCell>키</TableCell><TableCell>만료</TableCell><TableCell>상태</TableCell><TableCell align="right">작업</TableCell></TableRow></TableHead><TableBody>{keys.map(k=><TableRow key={k.id}><TableCell><Typography fontWeight={700}>{k.name}</Typography><Typography variant="body2" color="text.secondary">plx_{k.prefix}.•••••• · {k.scopes.join(', ')}</Typography></TableCell><TableCell>{k.expiresAt?.slice(0,10)||'무기한'}</TableCell><TableCell><Chip size="small" color={k.revokedAt?'default':'success'} label={k.revokedAt?'폐기됨':'활성'}/></TableCell><TableCell align="right">{!k.revokedAt&&<><Tooltip title="키 회전"><IconButton onClick={()=>void rotate(k.id)}><RefreshOutlined/></IconButton></Tooltip><Tooltip title="키 폐기"><IconButton color="error" onClick={()=>void revoke(k.id)}><DeleteOutline/></IconButton></Tooltip></>}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></Grid></Grid>
    <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>개인 키 발급</DialogTitle><DialogContent><Stack spacing={2} sx={{mt:1}}><TextField fullWidth label="키 이름" placeholder="예: Claude Desktop MCP" value={name} onChange={e=>setName(e.target.value)}/><TextField fullWidth select SelectProps={{multiple:true}} label="허용 Scope" value={selectedScopes} onChange={e=>setSelectedScopes(typeof e.target.value==='string'?e.target.value.split(','):e.target.value)}>{policy.allowedScopes.map(scope=><MenuItem key={scope} value={scope}>{scope}</MenuItem>)}</TextField><TextField fullWidth label={`만료 (일, 최대 ${policy.maxLifetimeDays})`} type="number" inputProps={{min:1,max:policy.maxLifetimeDays}} value={expiresInDays} onChange={e=>setExpiresInDays(Number(e.target.value))}/><Alert severity="info">선택 Scope는 현재 사용자 권한과 관리자 정책의 교집합입니다. 키는 표시된 회전 중첩 기간 안에 교체하세요.</Alert></Stack></DialogContent><DialogActions sx={{p:3}}><Button onClick={()=>setOpen(false)}>취소</Button><Button variant="contained" onClick={issue} disabled={!name.trim()||selectedScopes.length===0||expiresInDays<1||expiresInDays>policy.maxLifetimeDays}>발급</Button></DialogActions></Dialog>
  </Box>
}
